Id b 4.1
bodyalis/PetFinder pull request #7
Opened 2024-08-21 20:44 UTC by bodyalis

2024-08-21 21:13 UTC, YaraOduvanchik requested changes

2024-08-21 21:13 UTC, YaraOduvanchik commented on backend/src/PetFinder.Domain/Models/Pet.cs
> +    public Volunteer Volunteer { get; private set; } = default!;
Это нужно убрать, мы будем взаимодействовать с животными через модель волонтёра

2024-08-21 21:13 UTC, YaraOduvanchik commented on backend/src/PetFinder.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.HasOne(p => p.Volunteer)
Убрать

2024-08-21 21:13 UTC, YaraOduvanchik commented on backend/src/PetFinder.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.ToTable(t =>
Нужно убрать, валидация будет происходить в дургом месте.
Лучше используй ToTable, чтобы давать название таблице:
builder.ToTable("pets");

2024-08-21 21:13 UTC, YaraOduvanchik commented on backend/src/PetFinder.Infrastructure/Configurations/VolunteerConfiguration.cs
> +        builder.ToTable(t =>
То же самое, это нужно убрать

2024-08-22 06:07 UTC, bodyalis commented on backend/src/PetFinder.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.ToTable(t =>
![image](https://github.com/user-attachments/assets/9aa926f9-e2b8-4b48-b8e2-aaa5a3317694)

2024-08-22 06:08 UTC, bodyalis commented on backend/src/PetFinder.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.ToTable(t =>
> Нужно убрать, валидация будет происходить в дургом месте. Лучше используй ToTable, чтобы давать название таблице: builder.ToTable("pets");

Это не валидация, а ограничение. Почему я должен его убрать?

2024-08-22 06:22 UTC, KirillSachkov requested changes

2024-08-22 06:22 UTC, KirillSachkov commented on backend/src/PetFinder.Infrastructure/Configurations/PetConfiguration.cs
> +        builder.ToTable(t =>
Такие ограничения можно добавлять

2024-08-22 06:22 UTC, KirillSachkov commented on backend/src/PetFinder.Infrastructure/Configurations/VolunteerConfiguration.cs
> +        builder.ToTable(t =>
Тоже можно оставить

2024-08-22 18:29 UTC, KirillSachkov approved these changes

2024-08-24 13:45 UTC, merged